In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/customer_support.csv")
df.head()

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [2]:
df.shape

(26872, 5)

In [3]:
df.columns

Index(['flags', 'instruction', 'category', 'intent', 'response'], dtype='str')

In [4]:
df["intent"].nunique()

27

In [5]:
df["category"].value_counts()

category
ACCOUNT         5986
ORDER           3988
REFUND          2992
INVOICE         1999
CONTACT         1999
PAYMENT         1998
FEEDBACK        1997
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
Name: count, dtype: int64

In [6]:
df["intent"].value_counts()

intent
check_invoice               1000
complaint                   1000
contact_customer_service    1000
edit_account                1000
switch_account              1000
check_payment_methods        999
contact_human_agent          999
delivery_period              999
get_invoice                  999
newsletter_subscription      999
payment_issue                999
registration_problems        999
cancel_order                 998
place_order                  998
track_refund                 998
change_order                 997
check_refund_policy          997
create_account               997
get_refund                   997
review                       997
set_up_shipping_address      997
delete_account               995
delivery_options             995
recover_password             995
track_order                  995
change_shipping_address      973
check_cancellation_fee       950
Name: count, dtype: int64

In [7]:
df.isna().sum()

flags          0
instruction    0
category       0
intent         0
response       0
dtype: int64

In [8]:
df[["instruction", "intent"]].sample(10, random_state=42)

,instruction,intent
9329,I can't talk with a human agent,contact_human_agent
4160,I have got to locate hte bills from {{Person N...,check_invoice
18500,"I cannot pay, help me to inform of a problem w...",payment_issue
8840,I want help speaking to customer service,contact_customer_service
5098,I try to see th accepted payment options,check_payment_methods
17250,where to sign up to the company nmewsletter,newsletter_subscription
3589,I'd like to see the withdrwaal fee how can i d...,check_cancellation_fee
9043,I want to speak with someone,contact_human_agent
15800,can you help me getting bill #85632?,get_invoice
4384,I don't know how to take a quick look at invoi...,check_invoice

In [9]:
X = df["instruction"]
y = df["intent"]

In [10]:
print(X.shape)
print(y.shape)

(26872,)
(26872,)

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
print(X_train.shape)
print(X_test.shape)

(21497,)
(5375,)

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

pipeline_logistic = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=2
        )
    ),
    (
        "modelo",
        LogisticRegression(
            max_iter=2000
        )
    )
])

In [14]:
pipeline_logistic.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(min_df=2, ngram_range=(1, 2))),
                ('modelo', LogisticRegression(max_iter=2000))])

In [15]:
previsoes = pipeline_logistic.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score, f1_score

accuracy = accuracy_score(y_test, previsoes)
macro_f1 = f1_score(y_test, previsoes, average="macro")

print("Accuracy:", accuracy)
print("Macro F1:", macro_f1)

Accuracy: 0.994046511627907
Macro F1: 0.994058929394015

In [17]:
from sklearn.metrics import classification_report

print(classification_report(y_test, previsoes))

                          precision    recall  f1-score   support

            cancel_order       1.00      0.98      0.99       200
            change_order       0.97      0.98      0.97       199
 change_shipping_address       0.99      1.00      1.00       195
  check_cancellation_fee       0.99      1.00      1.00       190
           check_invoice       0.97      1.00      0.99       200
   check_payment_methods       1.00      0.99      1.00       200
     check_refund_policy       1.00      0.99      1.00       199
               complaint       1.00      1.00      1.00       200
contact_customer_service       1.00      0.99      0.99       200
     contact_human_agent       0.99      0.99      0.99       200
          create_account       0.99      0.99      0.99       199
          delete_account       0.99      1.00      0.99       199
        delivery_options       1.00      1.00      1.00       199
         delivery_period       1.00      1.00      1.00       200
            edit_account       0.98      1.00      0.99       200
             get_invoice       1.00      0.97      0.99       200
              get_refund       0.99      1.00      0.99       199
 newsletter_subscription       1.00      1.00      1.00       200
           payment_issue       1.00      0.98      0.99       200
             place_order       1.00      0.99      1.00       200
        recover_password       1.00      1.00      1.00       199
   registration_problems       0.99      0.99      0.99       200
                  review       1.00      1.00      1.00       199
 set_up_shipping_address       1.00      1.00      1.00       199
          switch_account       1.00      0.99      1.00       200
             track_order       1.00      0.97      0.98       199
            track_refund       1.00      1.00      1.00       200

                accuracy                           0.99      5375
               macro avg       0.99      0.99      0.99      5375
            weighted avg       0.99      0.99      0.99      5375

In [18]:
erros = pd.DataFrame({
    "texto": X_test,
    "real": y_test,
    "previsto": previsoes
})

erros = erros[erros["real"] != erros["previsto"]]

erros.head(20)

,texto,real,previsto
15879,I do not know how I candownload my bill #37777,get_invoice,check_invoice
21728,help creating account,registration_problems,create_account
6860,am I entitled to a reimbursement?,check_refund_policy,get_refund
8438,I don't know what to do to speak with cusstome...,contact_customer_service,contact_human_agent
18023,need assistance reporting an issue with pyments,payment_issue,registration_problems
17941,where can I notify of problems with payent?,payment_issue,registration_problems
10501,I need a user,create_account,edit_account
10358,what do i have to do to createa premium account,create_account,delete_account
1523,can I update order00004587345?,change_order,change_shipping_address
15091,i cannot find bill #85632 can usendit to me,get_invoice,check_invoice
18276,i do not know what to do to report an issue wi...,payment_issue,registration_problems
5385,can uhelp me check the bloody allowed paymentm...,check_payment_methods,check_cancellation_fee
1226,update purchase732201349959,change_order,edit_account
24746,help me usew the freemium account,switch_account,delete_account
25729,could ya help me locae purchase {{Order Number}},track_order,change_order
1808,modify order00004587345,change_order,edit_account
1207,update purchase00123842,change_order,edit_account
25420,how can i tfack purchase {{Order Number}},track_order,change_order
9025,contactingassistant,contact_human_agent,get_refund
21259,issues creating account,registration_problems,create_account

In [19]:
len(erros)

32

In [20]:
erros.head(20)

,texto,real,previsto
15879,I do not know how I candownload my bill #37777,get_invoice,check_invoice
21728,help creating account,registration_problems,create_account
6860,am I entitled to a reimbursement?,check_refund_policy,get_refund
8438,I don't know what to do to speak with cusstome...,contact_customer_service,contact_human_agent
18023,need assistance reporting an issue with pyments,payment_issue,registration_problems
17941,where can I notify of problems with payent?,payment_issue,registration_problems
10501,I need a user,create_account,edit_account
10358,what do i have to do to createa premium account,create_account,delete_account
1523,can I update order00004587345?,change_order,change_shipping_address
15091,i cannot find bill #85632 can usendit to me,get_invoice,check_invoice
18276,i do not know what to do to report an issue wi...,payment_issue,registration_problems
5385,can uhelp me check the bloody allowed paymentm...,check_payment_methods,check_cancellation_fee
1226,update purchase732201349959,change_order,edit_account
24746,help me usew the freemium account,switch_account,delete_account
25729,could ya help me locae purchase {{Order Number}},track_order,change_order
1808,modify order00004587345,change_order,edit_account
1207,update purchase00123842,change_order,edit_account
25420,how can i tfack purchase {{Order Number}},track_order,change_order
9025,contactingassistant,contact_human_agent,get_refund
21259,issues creating account,registration_problems,create_account

In [21]:
erros[["real", "previsto"]].value_counts()

real                      previsto
get_invoice               check_invoice              5
track_order               change_order               4
payment_issue             registration_problems      3
change_order              edit_account               3
registration_problems     create_account             2
contact_customer_service  contact_human_agent        2
cancel_order              change_order               2
check_refund_policy       get_refund                 1
create_account            edit_account               1
                          delete_account             1
change_order              change_shipping_address    1
check_payment_methods     check_cancellation_fee     1
switch_account            delete_account             1
contact_human_agent       get_refund                 1
cancel_order              delete_account             1
track_order               check_invoice              1
place_order               change_order               1
track_order               track_refund               1
Name: count, dtype: int64

In [22]:
from sklearn.svm import LinearSVC

pipeline_svm = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=2
        )
    ),
    (
        "modelo",
        LinearSVC()
    )
])

In [23]:
pipeline_svm.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(min_df=2, ngram_range=(1, 2))),
                ('modelo', LinearSVC())])

In [24]:
accuracy_svm = accuracy_score(y_test, previsoes_svm)
macro_f1_svm = f1_score(y_test, previsoes_svm, average="macro")

print("Accuracy SVM:", accuracy_svm)
print("Macro F1 SVM:", macro_f1_svm)

NameError: name 'previsoes_svm' is not defined

In [25]:
previsoes_svm = pipeline_svm.predict(X_test)

In [26]:
accuracy_svm = accuracy_score(y_test, previsoes_svm)
macro_f1_svm = f1_score(y_test, previsoes_svm, average="macro")

print("Accuracy SVM:", accuracy_svm)
print("Macro F1 SVM:", macro_f1_svm)

Accuracy SVM: 0.9951627906976744
Macro F1 SVM: 0.9951728838388713

In [27]:
erros_svm = pd.DataFrame({
    "texto": X_test,
    "real": y_test,
    "previsto": previsoes_svm
})

erros_svm = erros_svm[erros_svm["real"] != erros_svm["previsto"]]

len(erros_svm)

26

In [28]:
erros_svm[["real", "previsto"]].value_counts()

real                      previsto
track_order               change_order               4
get_invoice               check_invoice              3
change_order              edit_account               3
payment_issue             registration_problems      2
cancel_order              change_order               2
delivery_period           delivery_options           1
registration_problems     create_account             1
                          payment_issue              1
check_refund_policy       get_refund                 1
create_account            edit_account               1
                          delete_account             1
change_order              change_shipping_address    1
switch_account            delete_account             1
cancel_order              delete_account             1
check_invoice             get_invoice                1
contact_customer_service  contact_human_agent        1
set_up_shipping_address   change_shipping_address    1
Name: count, dtype: int64

In [29]:
erros_svm.head(20)

,texto,real,previsto
13067,I am trying to find the shipping perod,delivery_period,delivery_options
15879,I do not know how I candownload my bill #37777,get_invoice,check_invoice
21728,help creating account,registration_problems,create_account
21577,need help informing of rergistration errors,registration_problems,payment_issue
6860,am I entitled to a reimbursement?,check_refund_policy,get_refund
18023,need assistance reporting an issue with pyments,payment_issue,registration_problems
10501,I need a user,create_account,edit_account
10358,what do i have to do to createa premium account,create_account,delete_account
1523,can I update order00004587345?,change_order,change_shipping_address
15091,i cannot find bill #85632 can usendit to me,get_invoice,check_invoice
18276,i do not know what to do to report an issue wi...,payment_issue,registration_problems
1226,update purchase732201349959,change_order,edit_account
24746,help me usew the freemium account,switch_account,delete_account
25729,could ya help me locae purchase {{Order Number}},track_order,change_order
1808,modify order00004587345,change_order,edit_account
1207,update purchase00123842,change_order,edit_account
25420,how can i tfack purchase {{Order Number}},track_order,change_order
166,would you give me information about cancelling...,cancel_order,delete_account
25503,i have got to locte order {{Order Number}},track_order,change_order
25306,lcate order {{Order Number}},track_order,change_order

In [30]:
from sklearn.model_selection import cross_val_score

cv_logistic = cross_val_score(
    pipeline_logistic,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

print(cv_logistic)
print("Macro F1 médio Logistic:", cv_logistic.mean())
print("Desvio padrão:", cv_logistic.std())

[0.99294687 0.99256544 0.99293659 0.99257019 0.99164969]
Macro F1 médio Logistic: 0.9925337571364178
Desvio padrão: 0.0004726207162377721

In [31]:
cv_svm = cross_val_score(
    pipeline_svm,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

print(cv_svm)
print("Macro F1 médio SVM:", cv_svm.mean())
print("Desvio padrão:", cv_svm.std())

[0.99517392 0.99498055 0.99405742 0.99498161 0.99238508]
Macro F1 médio SVM: 0.9943157152755365
Desvio padrão: 0.0010407715023896223

In [32]:
cv_logistic = cross_val_score(
    pipeline_logistic,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

print(cv_logistic)
print("Macro F1 médio Logistic:", cv_logistic.mean())
print("Desvio padrão:", cv_logistic.std())

[0.99294687 0.99256544 0.99293659 0.99257019 0.99164969]
Macro F1 médio Logistic: 0.9925337571364178
Desvio padrão: 0.0004726207162377721

In [33]:
pipeline_final = pipeline_svm

pipeline_final.fit(X, y)

Pipeline(steps=[('tfidf', TfidfVectorizer(min_df=2, ngram_range=(1, 2))),
                ('modelo', LinearSVC())])

In [34]:
import joblib

joblib.dump(
    pipeline_final,
    "../models/nlp_intent_classifier.joblib"
)

['../models/nlp_intent_classifier.joblib']

In [35]:
def prever_intent(texto):
    intent = pipeline_final.predict([texto])[0]
    return intent

In [36]:
prever_intent("I want to cancel my order")

'cancel_order'

In [37]:
print(prever_intent("Where is my package?"))
print(prever_intent("I forgot my password"))
print(prever_intent("I was charged but the payment failed"))
print(prever_intent("Can I get my money back?"))
print(prever_intent("I want to talk to a real person"))

delivery_period
recover_password
payment_issue
get_refund
contact_human_agent

In [38]:
intent_para_categoria = (
    df[["intent", "category"]]
    .drop_duplicates()
    .set_index("intent")["category"]
    .to_dict()
)

In [39]:
def prever_intent(texto):
    intent = pipeline_final.predict([texto])[0]
    categoria = intent_para_categoria[intent]

    return {
        "intent": intent,
        "category": categoria
    }

In [40]:
prever_intent("I forgot my password")

{'intent': 'recover_password', 'category': 'ACCOUNT'}

In [41]:
{
    "intent": "recover_password",
    "category": "ACCOUNT"
}

{'intent': 'recover_password', 'category': 'ACCOUNT'}

In [42]:
prever_intent("Where is my package?")

{'intent': 'delivery_period', 'category': 'DELIVERY'}

In [43]:
import numpy as np

def softmax(scores):
    exp_scores = np.exp(scores - np.max(scores))
    return exp_scores / exp_scores.sum()

In [44]:
def prever_intent(texto):
    intent = pipeline_final.predict([texto])[0]
    categoria = intent_para_categoria[intent]

    scores = pipeline_final.decision_function([texto])[0]
    probabilidades = softmax(scores)

    classes = pipeline_final.classes_
    indice = list(classes).index(intent)

    confianca = float(probabilidades[indice])

    return {
        "intent": intent,
        "category": categoria,
        "confidence": round(confianca * 100, 1)
    }

In [45]:
prever_intent("I forgot my password")

{'intent': 'recover_password', 'category': 'ACCOUNT', 'confidence': 19.7}

In [46]:
prever_intent("Where is my package?")

{'intent': 'delivery_period', 'category': 'DELIVERY', 'confidence': 7.9}

In [47]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

pipeline_svm_calibrado = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=2
        )
    ),
    (
        "modelo",
        CalibratedClassifierCV(
            LinearSVC(),
            method="sigmoid",
            cv=5
        )
    )
])

In [48]:
pipeline_svm_calibrado.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(min_df=2, ngram_range=(1, 2))),
                ('modelo',
                 CalibratedClassifierCV(cv=5, estimator=LinearSVC()))])

In [49]:
previsoes_calibradas = pipeline_svm_calibrado.predict(X_test)

In [50]:
accuracy_calibrada = accuracy_score(y_test, previsoes_calibradas)
macro_f1_calibrado = f1_score(
    y_test,
    previsoes_calibradas,
    average="macro"
)

print("Accuracy:", accuracy_calibrada)
print("Macro F1:", macro_f1_calibrado)

Accuracy: 0.9947906976744186
Macro F1: 0.9948039244448018

In [51]:
pipeline_final = pipeline_svm_calibrado

pipeline_final.fit(X, y)

Pipeline(steps=[('tfidf', TfidfVectorizer(min_df=2, ngram_range=(1, 2))),
                ('modelo',
                 CalibratedClassifierCV(cv=5, estimator=LinearSVC()))])

In [52]:
joblib.dump(
    pipeline_final,
    "../models/nlp_intent_classifier.joblib"
)

['../models/nlp_intent_classifier.joblib']

In [53]:
joblib.dump(
    intent_para_categoria,
    "../models/intent_to_category.joblib"
)

['../models/intent_to_category.joblib']

In [54]:
def prever_intent(texto):
    probabilidades = pipeline_final.predict_proba([texto])[0]

    indice = probabilidades.argmax()
    intent = pipeline_final.classes_[indice]

    categoria = intent_para_categoria[intent]
    confianca = float(probabilidades[indice])

    return {
        "intent": intent,
        "category": categoria,
        "confidence": round(confianca * 100, 1)
    }

In [55]:
print(prever_intent("I forgot my password"))
print(prever_intent("Where is my package?"))
print(prever_intent("I want to speak to a real person"))

{'intent': 'recover_password', 'category': 'ACCOUNT', 'confidence': 98.7}
{'intent': 'delivery_period', 'category': 'DELIVERY', 'confidence': 62.6}
{'intent': 'contact_human_agent', 'category': 'CONTACT', 'confidence': 98.5}

In [56]:
testes = [
    "I need help",
    "My order has not arrived yet",
    "Can you change the address for my order?",
    "I want my money back",
    "I cannot create an account",
    "What payment methods do you accept?",
    "I want to cancel everything",
    "Can I speak to customer support?"
]

for texto in testes:
    print(texto)
    print(prever_intent(texto))
    print()

I need help
{'intent': 'get_refund', 'category': 'REFUND', 'confidence': 27.5}

My order has not arrived yet
{'intent': 'create_account', 'category': 'ACCOUNT', 'confidence': 50.6}

Can you change the address for my order?
{'intent': 'change_shipping_address', 'category': 'SHIPPING', 'confidence': 99.5}

I want my money back
{'intent': 'get_refund', 'category': 'REFUND', 'confidence': 98.7}

I cannot create an account
{'intent': 'create_account', 'category': 'ACCOUNT', 'confidence': 93.0}

What payment methods do you accept?
{'intent': 'check_payment_methods', 'category': 'PAYMENT', 'confidence': 99.0}

I want to cancel everything
{'intent': 'cancel_order', 'category': 'ORDER', 'confidence': 50.9}

Can I speak to customer support?
{'intent': 'contact_customer_service', 'category': 'CONTACT', 'confidence': 99.3}

In [57]:
def prever_top3(texto):
    probabilidades = pipeline_final.predict_proba([texto])[0]
    classes = pipeline_final.classes_

    indices = probabilidades.argsort()[-3:][::-1]

    resultados = []

    for indice in indices:
        intent = classes[indice]

        resultados.append({
            "intent": intent,
            "category": intent_para_categoria[intent],
            "confidence": round(float(probabilidades[indice]) * 100, 1)
        })

    return resultados

In [58]:
print(prever_top3("My order has not arrived yet"))
print(prever_top3("I need help"))
print(prever_top3("I want to cancel everything"))

[{'intent': 'create_account', 'category': 'ACCOUNT', 'confidence': 50.6}, {'intent': 'recover_password', 'category': 'ACCOUNT', 'confidence': 8.7}, {'intent': 'place_order', 'category': 'ORDER', 'confidence': 8.2}]
[{'intent': 'get_refund', 'category': 'REFUND', 'confidence': 27.5}, {'intent': 'place_order', 'category': 'ORDER', 'confidence': 25.4}, {'intent': 'cancel_order', 'category': 'ORDER', 'confidence': 19.4}]
[{'intent': 'cancel_order', 'category': 'ORDER', 'confidence': 50.9}, {'intent': 'delete_account', 'category': 'ACCOUNT', 'confidence': 48.1}, {'intent': 'newsletter_subscription', 'category': 'SUBSCRIPTION', 'confidence': 0.5}]

In [59]:
from sentence_transformers import SentenceTransformer

modelo_embeddings = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [60]:
X_embeddings = modelo_embeddings.encode(
    df["instruction"].tolist(),
    show_progress_bar=True
)

X_embeddings.shape

Batches:   0%|          | 0/840 [00:00<?, ?it/s]

(26872, 384)

In [61]:
X_train_emb, X_test_emb, y_train_emb, y_test_emb = train_test_split(
    X_embeddings,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [62]:
modelo_semantico = LogisticRegression(
    max_iter=3000
)

modelo_semantico.fit(X_train_emb, y_train_emb)

LogisticRegression(max_iter=3000)

In [63]:
previsoes_semanticas = modelo_semantico.predict(X_test_emb)

accuracy_semantica = accuracy_score(
    y_test_emb,
    previsoes_semanticas
)

f1_semantico = f1_score(
    y_test_emb,
    previsoes_semanticas,
    average="macro"
)

print("Accuracy:", accuracy_semantica)
print("Macro F1:", f1_semantico)

Accuracy: 0.994046511627907
Macro F1: 0.9940457624937806

In [64]:
def prever_semantico(texto):
    embedding = modelo_embeddings.encode([texto])

    probabilidades = modelo_semantico.predict_proba(embedding)[0]
    indice = probabilidades.argmax()

    intent = modelo_semantico.classes_[indice]
    confianca = float(probabilidades[indice])

    return {
        "intent": intent,
        "category": intent_para_categoria[intent],
        "confidence": round(confianca * 100, 1)
    }

In [65]:
testes_semanticos = [
    "My order has not arrived yet",
    "I need help",
    "I want to cancel everything",
    "Where is my package?",
    "I forgot my password",
    "Can you change the address for my order?"
]

for texto in testes_semanticos:
    print(texto)
    print(prever_semantico(texto))
    print()

My order has not arrived yet
{'intent': 'delivery_period', 'category': 'DELIVERY', 'confidence': 63.7}

I need help
{'intent': 'place_order', 'category': 'ORDER', 'confidence': 34.1}

I want to cancel everything
{'intent': 'cancel_order', 'category': 'ORDER', 'confidence': 42.8}

Where is my package?
{'intent': 'delivery_options', 'category': 'DELIVERY', 'confidence': 39.3}

I forgot my password
{'intent': 'recover_password', 'category': 'ACCOUNT', 'confidence': 96.8}

Can you change the address for my order?
{'intent': 'change_shipping_address', 'category': 'SHIPPING', 'confidence': 91.0}

In [66]:
import joblib

joblib.dump(
    modelo_semantico,
    "../models/semantic_intent_classifier.joblib"
)

['../models/semantic_intent_classifier.joblib']

In [67]:
joblib.dump(
    intent_para_categoria,
    "../models/intent_to_category.joblib"
)

['../models/intent_to_category.joblib']

In [68]:
from sklearn.linear_model import LogisticRegression

modelo_semantico_final = LogisticRegression(
    max_iter=3000
)

modelo_semantico_final.fit(X_embeddings, y)

LogisticRegression(max_iter=3000)

In [69]:
import joblib

joblib.dump(
    modelo_semantico_final,
    "../models/semantic_intent_classifier.joblib"
)

joblib.dump(
    intent_para_categoria,
    "../models/intent_to_category.joblib"
)

['../models/intent_to_category.joblib']

In [70]:
def prever_semantico_final(texto):
    embedding = modelo_embeddings.encode([texto])

    probabilidades = modelo_semantico_final.predict_proba(embedding)[0]
    classes = modelo_semantico_final.classes_

    indices_top3 = probabilidades.argsort()[-3:][::-1]

    top3 = []

    for indice in indices_top3:
        intent = classes[indice]

        top3.append({
            "intent": intent,
            "category": intent_para_categoria[intent],
            "confidence": round(float(probabilidades[indice]) * 100, 1)
        })

    principal = top3[0]

    if principal["confidence"] >= 70:
        nivel = "High"
    elif principal["confidence"] >= 40:
        nivel = "Medium"
    else:
        nivel = "Low"

    return {
        "intent": principal["intent"],
        "category": principal["category"],
        "confidence": principal["confidence"],
        "confidence_level": nivel,
        "top_3": top3
    }

In [71]:
prever_semantico_final("My order has not arrived yet")

{'intent': 'delivery_period',
 'category': 'DELIVERY',
 'confidence': 65.7,
 'confidence_level': 'Medium',
 'top_3': [{'intent': 'delivery_period',
   'category': 'DELIVERY',
   'confidence': 65.7},
  {'intent': 'place_order', 'category': 'ORDER', 'confidence': 8.7},
  {'intent': 'track_order', 'category': 'ORDER', 'confidence': 6.1}]}